{
 "title": "PostgreSQL",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TPS",
   "type": "graph",
   "description": "Transactions per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_postgres_egress_postgres_transactions_commit[1m])",
     "legendFormat": "Commits"
    },
    {
     "expr": "rate(envoy_postgres_egress_postgres_transactions_rollback[1m])",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Reads and Writes",
   "type": "graph",
   "description": "Reads and Writes per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(envoy_postgres_egress_postgres_statements_update[1m])+rate(envoy_postgres_egress_postgres_statements_insert[1m])+rate(envoy_postgres_egress_postgres_statements_delete[1m]))",
     "legendFormat": "Writes"
    },
    {
     "expr": "rate(envoy_postgres_egress_postgres_statements_select[1m])",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Statements",
   "type": "graph",
   "description": "Statements per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_postgres_egress_postgres_statements_select[1m])",
     "legendFormat": "Select"
    },
    {
     "expr": "rate(envoy_postgres_egress_postgres_statements_insert[1m])",
     "legendFormat": "Insert"
    },
    {
     "expr": "rate(envoy_postgres_egress_postgres_statements_update[1m])",
     "legendFormat": "Update"
    },
    {
     "expr": "rate(envoy_postgres_egress_postgres_statements_delete[1m])",
     "legendFormat": "Delete"
    },
    {
     "expr": "rate(envoy_postgres_egress_postgres_statements_other[1m])",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Frontend and Backend",
   "type": "graph",
   "description": "Frontend and Backend messages per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_postgres_egress_postgres_messages_frontend[1m])",
     "legendFormat": "Frontend"
    },
    {
     "expr": "rate(envoy_postgres_egress_postgres_messages_backend[1m])",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "description": "Sessions per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_postgres_egress_postgres_sessions[1m])",
     "legendFormat": "Frontend"
    }
   ]
  }
 ]
}